name: tfvarenv plan workflow

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  validate:
    runs-on: ubuntu-latest

    environment: ${{ github.event.pull_request.base.ref == 'main' && 'prd' || 'dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.0
      
      - name: Setup tfvarenv
        uses: marcy326/tfvarenv@v0
        with:
          version: v0.1.2

      - name: Plan Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform init -backend-config=envs/${{ vars.env }}/${{ vars.env }}.tfbackend
          tfvarenv plan ${{ vars.env }} --remote