name: tfvarenv plan workflow

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  validate:
    runs-on: ubuntu-latest

    environment: ${{ github.event.pull_request.base.ref == 'main' && 'prd' || 'dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.0
      
      - name: Setup tfvarenv
        uses: marcy326/tfvarenv@v0
        with:
          version: v0.2.2

      - name: Plan Terraform
        run: |
          tfvarenv use ${{ vars.env }}
          tfvarenv plan ${{ vars.env }} --remote